apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.4
  name: cachedimages.kuik.enix.io
spec:
  group: kuik.enix.io
  names:
    kind: CachedImage
    listKind: CachedImageList
    plural: cachedimages
    shortNames:
    - ci
    singular: cachedimage
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .status.isCached
      name: Cached
      type: boolean
    - jsonPath: .spec.retain
      name: Retain
      type: boolean
    - jsonPath: .spec.expiresAt
      name: Expires at
      type: string
    - jsonPath: .status.usedBy.count
      name: Pods count
      type: integer
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.progress.available
      name: Downloaded
      type: integer
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CachedImage is the Schema for the cachedimages API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: CachedImageSpec defines the desired state of CachedImage.
            properties:
              expiresAt:
                description: ExpiresAt is the time when the image should be deleted
                  from cache if not in use (unset when the image is used again)
                format: date-time
                type: string
              retain:
                description: Retain defines if the image should be retained in cache
                  even when not used (will prevent ExpiresAt to be populated)
                type: boolean
              sourceImage:
                description: SourceImage is the path of the image to cache
                type: string
            required:
            - sourceImage
            type: object
          status:
            description: CachedImageStatus defines the observed state of CachedImage.
            properties:
              availableUpstream:
                description: AvailableUpstream indicate whether if the referenced
                  image is available upstream or not
                type: boolean
              digest:
                description: Digest is the digest of the cached image
                type: string
              isCached:
                description: IsCached indicate whether the image is already cached
                  or not
                type: boolean
              lastSeenUpstream:
                description: LastSeenUpstream is the last time the referenced image
                  has been seen upstream
                format: date-time
                type: string
              lastSuccessfulPull:
                description: LastSuccessfulPull is the last time the upstream image
                  has been successfully cached
                format: date-time
                type: string
              lastSync:
                description: LastSync is the last time the remote image digest has
                  been checked
                format: date-time
                type: string
              phase:
                description: Phase is the current phase of the image
                type: string
              upToDate:
                description: UpToDate indicate whether if the cached image is up to
                  date with the upstream one or not
                type: boolean
              upstreamDigest:
                description: UpstreamDigest is the upstream image digest
                type: string
              progress:
                type: object
                properties:
                  total:
                    type: integer
                    description: Total size of the compressed blob in bytes, including all layers, excluding all manifests.
                  available:
                    type: integer
                    description: Total downloaded / available size of the compressed blob in bytes, including all layers, excluding all manifests.
              usedBy:
                description: UsedBy is the list of pods using this image
                properties:
                  count:
                    description: |-
                      Count is the number of pods using this image

                      jsonpath function .length() is not implemented, so the count field is required to display pods count in additionalPrinterColumns
                      see https://github.com/kubernetes-sigs/controller-tools/issues/447
                    type: integer
                  pods:
                    description: Pods is a list of reference to pods using this CachedImage
                    items:
                      properties:
                        namespacedName:
                          description: NamespacedName is the namespaced name of a
                            pod (namespace/name)
                          type: string
                      type: object
                    type: array
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
