apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  name: imagemirrors.kuik.enix.io
spec:
  group: kuik.enix.io
  names:
    kind: ImageMirror
    listKind: ImageMirrorList
    plural: imagemirrors
    shortNames:
    - imgmir
    singular: imagemirror
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.path
      name: Image
      type: string
    - jsonPath: .spec.registry
      name: From
      type: string
    - jsonPath: .spec.targetRegistry
      name: To
      type: string
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ImageMirror is the Schema for the imagemirrors API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ImageMirrorSpec defines the desired state of ImageMirror.
            properties:
              path:
                description: Path is a string identifying the image in a registry
                type: string
              registry:
                description: Registry is the registry where the image is located
                type: string
              targetRegistry:
                description: TargetRegistry is the registry on which the image should
                  be mirrored
                type: string
            required:
            - path
            - registry
            - targetRegistry
            type: object
          status:
            description: ImageMirrorStatus defines the observed state of ImageMirror.
            properties:
              phase:
                description: Phase represents the current phase of the ImageMirror
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
