# This rule is not used by the project kube-image-keeper itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over kuik.enix.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-image-keeper
    app.kubernetes.io/managed-by: kustomize
  name: kuik-clusterimagesetmirror-admin-role
rules:
- apiGroups:
  - kuik.enix.io
  resources:
  - clusterimagesetmirrors
  verbs:
  - '*'
- apiGroups:
  - kuik.enix.io
  resources:
  - clusterimagesetmirrors/status
  verbs:
  - get
