apiVersion: kuik.enix.io/v1alpha1ext1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/name: repository
    app.kubernetes.io/instance: repository-sample
    app.kubernetes.io/part-of: kube-image-keeper
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-image-keeper
  name: repository-sample
spec:
  # TODO(user): Add fields here
