apiVersion: kuik.enix.io/v1alpha1ext1
kind: CachedImage
metadata:
  labels:
    app.kubernetes.io/name: cachedimage
    app.kubernetes.io/instance: cachedimage-sample
    app.kubernetes.io/part-of: kube-image-keeper
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-image-keeper
  name: cachedimage-sample
spec:
  # TODO(user): Add fields here
