## Append samples of your project ##
resources:
- kuik_v1alpha1_image.yaml
- kuik_v1alpha1_registrymonitor.yaml
- kuik_v1alpha1_imagemonitor.yaml
- kuik_v1alpha1_imagemirror.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
