{{- if eq (include "kube-image-keeper.registry-stateless-mode" .) "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-image-keeper.fullname" . }}-registry
  labels:
    {{- include "kube-image-keeper.registry-labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kube-image-keeper.registry-selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.registry.replicas }}
  template:
    metadata:
      {{- with .Values.registry.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-image-keeper.registry-selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.registry.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.registry.priorityClassName }}
      priorityClassName: {{ .Values.registry.priorityClassName | quote }}
      {{- end }}
      serviceAccountName: {{ include "kube-image-keeper.fullname" . }}-registry
      securityContext:
        {{- toYaml .Values.registry.podSecurityContext | nindent 8 }}
      containers:
        - name: registry
          securityContext:
            {{- toYaml .Values.registry.securityContext | nindent 12 }}
          image: "{{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}"
          imagePullPolicy: {{ .Values.registry.image.pullPolicy }}
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            {{- toYaml .Values.registry.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "kube-image-keeper.fullname" . }}-registry-configmap
            - configMapRef:
                name: {{ include "kube-image-keeper.fullname" . }}-registry-stateless-configmap
          env:
            - name: REGISTRY_HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "kube-image-keeper.fullname" . }}-registry-http-secret
                  key: secret
            {{ $s3KeysSecretName := .Values.registry.persistence.s3ExistingSecret | default "kube-image-keeper-s3-registry-keys" }}
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: {{ $s3KeysSecretName }}
                  key: accessKey
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ $s3KeysSecretName }}
                  key: secretKey
          {{- with .Values.registry.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.registry.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.registry.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registry.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registry.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
