- apiGroups:
  - kuik.enix.io
  resources:
  - clusterimagesetmirrors
  - imagesetmirrors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuik.enix.io
  resources:
  - clusterimagesetmirrors/finalizers
  - imagesetmirrors/finalizers
  verbs:
  - update
- apiGroups:
  - kuik.enix.io
  resources:
  - clusterimagesetmirrors/status
  - imagesetmirrors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kuik.enix.io
  resources:
  - clusterreplicatedimagesets
  - replicatedimagesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuik.enix.io
  resources:
  - clusterreplicatedimagesets/status
  - replicatedimagesets/status
  verbs:
  - get
