---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  name: clusterreplicatedimagesets.kuik.enix.io
spec:
  group: kuik.enix.io
  names:
    kind: ClusterReplicatedImageSet
    listKind: ClusterReplicatedImageSetList
    plural: clusterreplicatedimagesets
    shortNames:
    - cris
    singular: clusterreplicatedimageset
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterReplicatedImageSet is the Schema for the clusterreplicatedimagesets
          API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ClusterReplicatedImageSetSpec defines the desired state of
              ClusterReplicatedImageSet.
            properties:
              upstreams:
                items:
                  properties:
                    credentialSecret:
                      description: CredentialSecret is the image pull secret to use
                        for matching images
                      properties:
                        name:
                          description: Name is the name of the secret
                          type: string
                        namespace:
                          description: |-
                            Namespace is the namespace where the secret is located.
                            This value is ignored for namespaced resources and the namespace of the parent object is used instead.
                          type: string
                      type: object
                    imageMatcher:
                      description: ImageMatcher is a regexp identifying the image
                        in a registry
                      type: string
                    path:
                      description: Path is a string identifying the image in a registry
                      type: string
                    registry:
                      description: Registry is the registry where the image is located
                      type: string
                  required:
                  - imageMatcher
                  - path
                  - registry
                  type: object
                type: array
            type: object
          status:
            description: ClusterReplicatedImageSetStatus defines the observed state
              of ClusterReplicatedImageSet.
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
